# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missile',
            old_name='design_name',
            new_name='name',
        ),
    ]
